baseURL = "https://xingwei4225.github.io/"

languageCode = "en-us"
DefaultContentLanguage = "ch"
title = "保多多—文档中心"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "ch"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
#
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
editURL = "https://github.com/xingwei4225/vlife-docs/tree/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>行云天下</label>"
url = "http://www.witgo.cn"
weight = 10


[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>APP下载</label>"
url = "http://a.app.qq.com/o/simple.jsp?pkgname=com.witgo.env&g_f=991653"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Demo</label>"
url = "https://themes.gohugo.io/theme/docdock/"
weight = 12


[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> <label>docdock</label>"
identifier = "ds"
url = "https://github.com/vjeantet/hugo-theme-docdock"
weight = 13
